//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TRealTimeDataSync.HB_TRealtimeData {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRealtimeDataService", Namespace="http://tempuri.org/")]
    public partial class CMDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MonitorBcmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonitorBcmsForSkillOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonitorTrunkTrafficOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonitorBcmsSystemOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsRunningOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsConnectedToCMOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CMDataService() {
            this.Url = global::TRealTimeDataSync.Properties.Settings.Default.TRealTimeDataSync_HB_TRealtimeData_CMDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MonitorBcmsCompletedEventHandler MonitorBcmsCompleted;
        
        /// <remarks/>
        public event MonitorBcmsForSkillCompletedEventHandler MonitorBcmsForSkillCompleted;
        
        /// <remarks/>
        public event MonitorTrunkTrafficCompletedEventHandler MonitorTrunkTrafficCompleted;
        
        /// <remarks/>
        public event MonitorBcmsSystemCompletedEventHandler MonitorBcmsSystemCompleted;
        
        /// <remarks/>
        public event IsRunningCompletedEventHandler IsRunningCompleted;
        
        /// <remarks/>
        public event IsConnectedToCMCompletedEventHandler IsConnectedToCMCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/MonitorBcms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
        public BcmsDashboard[] MonitorBcms() {
            object[] results = this.Invoke("MonitorBcms", new object[0]);
            return ((BcmsDashboard[])(results[0]));
        }
        
        /// <remarks/>
        public void MonitorBcmsAsync() {
            this.MonitorBcmsAsync(null);
        }
        
        /// <remarks/>
        public void MonitorBcmsAsync(object userState) {
            if ((this.MonitorBcmsOperationCompleted == null)) {
                this.MonitorBcmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonitorBcmsOperationCompleted);
            }
            this.InvokeAsync("MonitorBcms", new object[0], this.MonitorBcmsOperationCompleted, userState);
        }
        
        private void OnMonitorBcmsOperationCompleted(object arg) {
            if ((this.MonitorBcmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonitorBcmsCompleted(this, new MonitorBcmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/MonitorBcmsForSkill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BcmsDashboard MonitorBcmsForSkill([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string skillToMonitor) {
            object[] results = this.Invoke("MonitorBcmsForSkill", new object[] {
                        skillToMonitor});
            return ((BcmsDashboard)(results[0]));
        }
        
        /// <remarks/>
        public void MonitorBcmsForSkillAsync(string skillToMonitor) {
            this.MonitorBcmsForSkillAsync(skillToMonitor, null);
        }
        
        /// <remarks/>
        public void MonitorBcmsForSkillAsync(string skillToMonitor, object userState) {
            if ((this.MonitorBcmsForSkillOperationCompleted == null)) {
                this.MonitorBcmsForSkillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonitorBcmsForSkillOperationCompleted);
            }
            this.InvokeAsync("MonitorBcmsForSkill", new object[] {
                        skillToMonitor}, this.MonitorBcmsForSkillOperationCompleted, userState);
        }
        
        private void OnMonitorBcmsForSkillOperationCompleted(object arg) {
            if ((this.MonitorBcmsForSkillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonitorBcmsForSkillCompleted(this, new MonitorBcmsForSkillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/MonitorTrunkTraffic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
        public TrunkGroupTraffic[] MonitorTrunkTraffic() {
            object[] results = this.Invoke("MonitorTrunkTraffic", new object[0]);
            return ((TrunkGroupTraffic[])(results[0]));
        }
        
        /// <remarks/>
        public void MonitorTrunkTrafficAsync() {
            this.MonitorTrunkTrafficAsync(null);
        }
        
        /// <remarks/>
        public void MonitorTrunkTrafficAsync(object userState) {
            if ((this.MonitorTrunkTrafficOperationCompleted == null)) {
                this.MonitorTrunkTrafficOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonitorTrunkTrafficOperationCompleted);
            }
            this.InvokeAsync("MonitorTrunkTraffic", new object[0], this.MonitorTrunkTrafficOperationCompleted, userState);
        }
        
        private void OnMonitorTrunkTrafficOperationCompleted(object arg) {
            if ((this.MonitorTrunkTrafficCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonitorTrunkTrafficCompleted(this, new MonitorTrunkTrafficCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/MonitorBcmsSystem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
        public BcmsSystem[] MonitorBcmsSystem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string skillName) {
            object[] results = this.Invoke("MonitorBcmsSystem", new object[] {
                        skillName});
            return ((BcmsSystem[])(results[0]));
        }
        
        /// <remarks/>
        public void MonitorBcmsSystemAsync(string skillName) {
            this.MonitorBcmsSystemAsync(skillName, null);
        }
        
        /// <remarks/>
        public void MonitorBcmsSystemAsync(string skillName, object userState) {
            if ((this.MonitorBcmsSystemOperationCompleted == null)) {
                this.MonitorBcmsSystemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonitorBcmsSystemOperationCompleted);
            }
            this.InvokeAsync("MonitorBcmsSystem", new object[] {
                        skillName}, this.MonitorBcmsSystemOperationCompleted, userState);
        }
        
        private void OnMonitorBcmsSystemOperationCompleted(object arg) {
            if ((this.MonitorBcmsSystemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonitorBcmsSystemCompleted(this, new MonitorBcmsSystemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/IsRunning", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsRunning(out bool IsRunningResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsRunningResultSpecified) {
            object[] results = this.Invoke("IsRunning", new object[0]);
            IsRunningResult = ((bool)(results[0]));
            IsRunningResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsRunningAsync() {
            this.IsRunningAsync(null);
        }
        
        /// <remarks/>
        public void IsRunningAsync(object userState) {
            if ((this.IsRunningOperationCompleted == null)) {
                this.IsRunningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsRunningOperationCompleted);
            }
            this.InvokeAsync("IsRunning", new object[0], this.IsRunningOperationCompleted, userState);
        }
        
        private void OnIsRunningOperationCompleted(object arg) {
            if ((this.IsRunningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsRunningCompleted(this, new IsRunningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRealtimeDataService/IsConnectedToCM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsConnectedToCM(out bool IsConnectedToCMResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsConnectedToCMResultSpecified) {
            object[] results = this.Invoke("IsConnectedToCM", new object[0]);
            IsConnectedToCMResult = ((bool)(results[0]));
            IsConnectedToCMResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsConnectedToCMAsync() {
            this.IsConnectedToCMAsync(null);
        }
        
        /// <remarks/>
        public void IsConnectedToCMAsync(object userState) {
            if ((this.IsConnectedToCMOperationCompleted == null)) {
                this.IsConnectedToCMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsConnectedToCMOperationCompleted);
            }
            this.InvokeAsync("IsConnectedToCM", new object[0], this.IsConnectedToCMOperationCompleted, userState);
        }
        
        private void OnIsConnectedToCMOperationCompleted(object arg) {
            if ((this.IsConnectedToCMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsConnectedToCMCompleted(this, new IsConnectedToCMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
    public partial class BcmsDashboard {
        
        private string aCDField;
        
        private string aCWField;
        
        private string aUXField;
        
        private string abandCallsField;
        
        private string abandCallsSummaryField;
        
        private decimal abandonPercentageField;
        
        private bool abandonPercentageFieldSpecified;
        
        private string accptedSLField;
        
        private string acdCallsSummaryField;
        
        private AgentData[] agentDataField;
        
        private string availField;
        
        private string avgAbandTimeField;
        
        private string avgHandlingTimeField;
        
        private string callsWaitingField;
        
        private string channelField;
        
        private string dateField;
        
        private string extnField;
        
        private string oldestCallField;
        
        private string otherField;
        
        private string percentageInSLField;
        
        private string slField;
        
        private string skillField;
        
        private string skillNameField;
        
        private string staffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ACD {
            get {
                return this.aCDField;
            }
            set {
                this.aCDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ACW {
            get {
                return this.aCWField;
            }
            set {
                this.aCWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AUX {
            get {
                return this.aUXField;
            }
            set {
                this.aUXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbandCalls {
            get {
                return this.abandCallsField;
            }
            set {
                this.abandCallsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbandCallsSummary {
            get {
                return this.abandCallsSummaryField;
            }
            set {
                this.abandCallsSummaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal AbandonPercentage {
            get {
                return this.abandonPercentageField;
            }
            set {
                this.abandonPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AbandonPercentageSpecified {
            get {
                return this.abandonPercentageFieldSpecified;
            }
            set {
                this.abandonPercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccptedSL {
            get {
                return this.accptedSLField;
            }
            set {
                this.accptedSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AcdCallsSummary {
            get {
                return this.acdCallsSummaryField;
            }
            set {
                this.acdCallsSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AgentData[] AgentData {
            get {
                return this.agentDataField;
            }
            set {
                this.agentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Avail {
            get {
                return this.availField;
            }
            set {
                this.availField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgAbandTime {
            get {
                return this.avgAbandTimeField;
            }
            set {
                this.avgAbandTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgHandlingTime {
            get {
                return this.avgHandlingTimeField;
            }
            set {
                this.avgHandlingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallsWaiting {
            get {
                return this.callsWaitingField;
            }
            set {
                this.callsWaitingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Extn {
            get {
                return this.extnField;
            }
            set {
                this.extnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OldestCall {
            get {
                return this.oldestCallField;
            }
            set {
                this.oldestCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PercentageInSL {
            get {
                return this.percentageInSLField;
            }
            set {
                this.percentageInSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Skill {
            get {
                return this.skillField;
            }
            set {
                this.skillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SkillName {
            get {
                return this.skillNameField;
            }
            set {
                this.skillNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Staff {
            get {
                return this.staffField;
            }
            set {
                this.staffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
    public partial class AgentData {
        
        private string loginIdField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
    public partial class BcmsSystem {
        
        private string abandandCallsField;
        
        private string acdCallsField;
        
        private string availableAgentsField;
        
        private string avgAbandTimeField;
        
        private string avgAfterCallField;
        
        private string avgSpeedAnswerField;
        
        private string avgTalkTimeField;
        
        private string callsWaitingField;
        
        private string dateField;
        
        private string oldestCallField;
        
        private string percentageSLField;
        
        private string skillNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AbandandCalls {
            get {
                return this.abandandCallsField;
            }
            set {
                this.abandandCallsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AcdCalls {
            get {
                return this.acdCallsField;
            }
            set {
                this.acdCallsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvailableAgents {
            get {
                return this.availableAgentsField;
            }
            set {
                this.availableAgentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgAbandTime {
            get {
                return this.avgAbandTimeField;
            }
            set {
                this.avgAbandTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgAfterCall {
            get {
                return this.avgAfterCallField;
            }
            set {
                this.avgAfterCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgSpeedAnswer {
            get {
                return this.avgSpeedAnswerField;
            }
            set {
                this.avgSpeedAnswerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AvgTalkTime {
            get {
                return this.avgTalkTimeField;
            }
            set {
                this.avgTalkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallsWaiting {
            get {
                return this.callsWaitingField;
            }
            set {
                this.callsWaitingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OldestCall {
            get {
                return this.oldestCallField;
            }
            set {
                this.oldestCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PercentageSL {
            get {
                return this.percentageSLField;
            }
            set {
                this.percentageSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SkillName {
            get {
                return this.skillNameField;
            }
            set {
                this.skillNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
    public partial class TrunkGroupTraffic {
        
        private int activeMembersField;
        
        private bool activeMembersFieldSpecified;
        
        private int callsWaitingField;
        
        private bool callsWaitingFieldSpecified;
        
        private string dateField;
        
        private int queueLengthField;
        
        private bool queueLengthFieldSpecified;
        
        private int trunkGroupField;
        
        private bool trunkGroupFieldSpecified;
        
        private int trunkGroupSizeField;
        
        private bool trunkGroupSizeFieldSpecified;
        
        private int activeMembersField1;
        
        private bool activeMembersField1Specified;
        
        private string dateField1;
        
        private int queueLengthField1;
        
        private bool queueLengthField1Specified;
        
        private int trunkGroupField1;
        
        private bool trunkGroupField1Specified;
        
        private int trunkGroupSizeField1;
        
        private bool trunkGroupSizeField1Specified;
        
        /// <remarks/>
        public int ActiveMembers {
            get {
                return this.activeMembersField;
            }
            set {
                this.activeMembersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveMembersSpecified {
            get {
                return this.activeMembersFieldSpecified;
            }
            set {
                this.activeMembersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CallsWaiting {
            get {
                return this.callsWaitingField;
            }
            set {
                this.callsWaitingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CallsWaitingSpecified {
            get {
                return this.callsWaitingFieldSpecified;
            }
            set {
                this.callsWaitingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public int QueueLength {
            get {
                return this.queueLengthField;
            }
            set {
                this.queueLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QueueLengthSpecified {
            get {
                return this.queueLengthFieldSpecified;
            }
            set {
                this.queueLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TrunkGroup {
            get {
                return this.trunkGroupField;
            }
            set {
                this.trunkGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrunkGroupSpecified {
            get {
                return this.trunkGroupFieldSpecified;
            }
            set {
                this.trunkGroupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TrunkGroupSize {
            get {
                return this.trunkGroupSizeField;
            }
            set {
                this.trunkGroupSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrunkGroupSizeSpecified {
            get {
                return this.trunkGroupSizeFieldSpecified;
            }
            set {
                this.trunkGroupSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int activeMembers {
            get {
                return this.activeMembersField1;
            }
            set {
                this.activeMembersField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeMembersSpecified {
            get {
                return this.activeMembersField1Specified;
            }
            set {
                this.activeMembersField1Specified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField1;
            }
            set {
                this.dateField1 = value;
            }
        }
        
        /// <remarks/>
        public int queueLength {
            get {
                return this.queueLengthField1;
            }
            set {
                this.queueLengthField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queueLengthSpecified {
            get {
                return this.queueLengthField1Specified;
            }
            set {
                this.queueLengthField1Specified = value;
            }
        }
        
        /// <remarks/>
        public int trunkGroup {
            get {
                return this.trunkGroupField1;
            }
            set {
                this.trunkGroupField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trunkGroupSpecified {
            get {
                return this.trunkGroupField1Specified;
            }
            set {
                this.trunkGroupField1Specified = value;
            }
        }
        
        /// <remarks/>
        public int trunkGroupSize {
            get {
                return this.trunkGroupSizeField1;
            }
            set {
                this.trunkGroupSizeField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trunkGroupSizeSpecified {
            get {
                return this.trunkGroupSizeField1Specified;
            }
            set {
                this.trunkGroupSizeField1Specified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MonitorBcmsCompletedEventHandler(object sender, MonitorBcmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitorBcmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MonitorBcmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BcmsDashboard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BcmsDashboard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MonitorBcmsForSkillCompletedEventHandler(object sender, MonitorBcmsForSkillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitorBcmsForSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MonitorBcmsForSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BcmsDashboard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BcmsDashboard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MonitorTrunkTrafficCompletedEventHandler(object sender, MonitorTrunkTrafficCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitorTrunkTrafficCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MonitorTrunkTrafficCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrunkGroupTraffic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrunkGroupTraffic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void MonitorBcmsSystemCompletedEventHandler(object sender, MonitorBcmsSystemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MonitorBcmsSystemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MonitorBcmsSystemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BcmsSystem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BcmsSystem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IsRunningCompletedEventHandler(object sender, IsRunningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsRunningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsRunningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IsRunningResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsRunningResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IsConnectedToCMCompletedEventHandler(object sender, IsConnectedToCMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsConnectedToCMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsConnectedToCMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IsConnectedToCMResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsConnectedToCMResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591