//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BcmsDashboard", Namespace="http://schemas.datacontract.org/2004/07/CMDataCollector.Models")]
    [System.SerializableAttribute()]
    public partial class BcmsDashboard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AUXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbandCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccptedSLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvgAbandTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallsWaitingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldestCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACD {
            get {
                return this.ACDField;
            }
            set {
                if ((object.ReferenceEquals(this.ACDField, value) != true)) {
                    this.ACDField = value;
                    this.RaisePropertyChanged("ACD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACW {
            get {
                return this.ACWField;
            }
            set {
                if ((object.ReferenceEquals(this.ACWField, value) != true)) {
                    this.ACWField = value;
                    this.RaisePropertyChanged("ACW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUX {
            get {
                return this.AUXField;
            }
            set {
                if ((object.ReferenceEquals(this.AUXField, value) != true)) {
                    this.AUXField = value;
                    this.RaisePropertyChanged("AUX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbandCalls {
            get {
                return this.AbandCallsField;
            }
            set {
                if ((object.ReferenceEquals(this.AbandCallsField, value) != true)) {
                    this.AbandCallsField = value;
                    this.RaisePropertyChanged("AbandCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccptedSL {
            get {
                return this.AccptedSLField;
            }
            set {
                if ((object.ReferenceEquals(this.AccptedSLField, value) != true)) {
                    this.AccptedSLField = value;
                    this.RaisePropertyChanged("AccptedSL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avail {
            get {
                return this.AvailField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailField, value) != true)) {
                    this.AvailField = value;
                    this.RaisePropertyChanged("Avail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgAbandTime {
            get {
                return this.AvgAbandTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvgAbandTimeField, value) != true)) {
                    this.AvgAbandTimeField = value;
                    this.RaisePropertyChanged("AvgAbandTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallsWaiting {
            get {
                return this.CallsWaitingField;
            }
            set {
                if ((object.ReferenceEquals(this.CallsWaitingField, value) != true)) {
                    this.CallsWaitingField = value;
                    this.RaisePropertyChanged("CallsWaiting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extn {
            get {
                return this.ExtnField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtnField, value) != true)) {
                    this.ExtnField = value;
                    this.RaisePropertyChanged("Extn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldestCall {
            get {
                return this.OldestCallField;
            }
            set {
                if ((object.ReferenceEquals(this.OldestCallField, value) != true)) {
                    this.OldestCallField = value;
                    this.RaisePropertyChanged("OldestCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other {
            get {
                return this.OtherField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherField, value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SL {
            get {
                return this.SLField;
            }
            set {
                if ((object.ReferenceEquals(this.SLField, value) != true)) {
                    this.SLField = value;
                    this.RaisePropertyChanged("SL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skill {
            get {
                return this.SkillField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillField, value) != true)) {
                    this.SkillField = value;
                    this.RaisePropertyChanged("Skill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillName {
            get {
                return this.SkillNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNameField, value) != true)) {
                    this.SkillNameField = value;
                    this.RaisePropertyChanged("SkillName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBcmsDashboardService")]
    public interface IBcmsDashboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcmsDashboardService/MonitorBcms", ReplyAction="http://tempuri.org/IBcmsDashboardService/MonitorBcmsResponse")]
        TestApp.ServiceReference1.BcmsDashboard[] MonitorBcms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcmsDashboardService/MonitorBcmsForSkill", ReplyAction="http://tempuri.org/IBcmsDashboardService/MonitorBcmsForSkillResponse")]
        TestApp.ServiceReference1.BcmsDashboard MonitorBcmsForSkill(string skillToMonitor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBcmsDashboardServiceChannel : TestApp.ServiceReference1.IBcmsDashboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BcmsDashboardServiceClient : System.ServiceModel.ClientBase<TestApp.ServiceReference1.IBcmsDashboardService>, TestApp.ServiceReference1.IBcmsDashboardService {
        
        public BcmsDashboardServiceClient() {
        }
        
        public BcmsDashboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BcmsDashboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcmsDashboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcmsDashboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestApp.ServiceReference1.BcmsDashboard[] MonitorBcms() {
            return base.Channel.MonitorBcms();
        }
        
        public TestApp.ServiceReference1.BcmsDashboard MonitorBcmsForSkill(string skillToMonitor) {
            return base.Channel.MonitorBcmsForSkill(skillToMonitor);
        }
    }
}
