//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IBcmsHistoricalService")]
    public interface IBcmsHistoricalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBcmsHistoricalService/GetBcmsHistoricalData", ReplyAction="http://tempuri.org/IBcmsHistoricalService/GetBcmsHistoricalDataResponse")]
        CMDataCollector.BcmsHistoricalDashboard.BCMSSkill GetBcmsHistoricalData(string skillId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBcmsHistoricalServiceChannel : TestApp.ServiceReference3.IBcmsHistoricalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BcmsHistoricalServiceClient : System.ServiceModel.ClientBase<TestApp.ServiceReference3.IBcmsHistoricalService>, TestApp.ServiceReference3.IBcmsHistoricalService {
        
        public BcmsHistoricalServiceClient() {
        }
        
        public BcmsHistoricalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BcmsHistoricalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcmsHistoricalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BcmsHistoricalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CMDataCollector.BcmsHistoricalDashboard.BCMSSkill GetBcmsHistoricalData(string skillId) {
            return base.Channel.GetBcmsHistoricalData(skillId);
        }
    }
}
