//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDataCollector.THistoricalData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillData", Namespace="http://schemas.datacontract.org/2004/07/THistoricalData.Lib.Model")]
    [System.SerializableAttribute()]
    public partial class SkillData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AbandCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcceptableServiceLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcdCallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvgAbandTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvgSpeedAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvgStaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvgTalkTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlowInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FlowOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntvlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReportDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SwitchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAfterCallTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAuxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AbandCalls {
            get {
                return this.AbandCallsField;
            }
            set {
                if ((this.AbandCallsField.Equals(value) != true)) {
                    this.AbandCallsField = value;
                    this.RaisePropertyChanged("AbandCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcceptableServiceLevel {
            get {
                return this.AcceptableServiceLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptableServiceLevelField, value) != true)) {
                    this.AcceptableServiceLevelField = value;
                    this.RaisePropertyChanged("AcceptableServiceLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcdCalls {
            get {
                return this.AcdCallsField;
            }
            set {
                if ((this.AcdCallsField.Equals(value) != true)) {
                    this.AcdCallsField = value;
                    this.RaisePropertyChanged("AcdCalls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgAbandTime {
            get {
                return this.AvgAbandTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvgAbandTimeField, value) != true)) {
                    this.AvgAbandTimeField = value;
                    this.RaisePropertyChanged("AvgAbandTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgSpeedAnswer {
            get {
                return this.AvgSpeedAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AvgSpeedAnswerField, value) != true)) {
                    this.AvgSpeedAnswerField = value;
                    this.RaisePropertyChanged("AvgSpeedAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvgStaff {
            get {
                return this.AvgStaffField;
            }
            set {
                if ((this.AvgStaffField.Equals(value) != true)) {
                    this.AvgStaffField = value;
                    this.RaisePropertyChanged("AvgStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgTalkTime {
            get {
                return this.AvgTalkTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvgTalkTimeField, value) != true)) {
                    this.AvgTalkTimeField = value;
                    this.RaisePropertyChanged("AvgTalkTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateInt {
            get {
                return this.DateIntField;
            }
            set {
                if ((object.ReferenceEquals(this.DateIntField, value) != true)) {
                    this.DateIntField = value;
                    this.RaisePropertyChanged("DateInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowIn {
            get {
                return this.FlowInField;
            }
            set {
                if ((this.FlowInField.Equals(value) != true)) {
                    this.FlowInField = value;
                    this.RaisePropertyChanged("FlowIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowOut {
            get {
                return this.FlowOutField;
            }
            set {
                if ((this.FlowOutField.Equals(value) != true)) {
                    this.FlowOutField = value;
                    this.RaisePropertyChanged("FlowOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((object.ReferenceEquals(this.IntervalField, value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intvl {
            get {
                return this.IntvlField;
            }
            set {
                if ((object.ReferenceEquals(this.IntvlField, value) != true)) {
                    this.IntvlField = value;
                    this.RaisePropertyChanged("Intvl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDateTime {
            get {
                return this.ReportDateTimeField;
            }
            set {
                if ((this.ReportDateTimeField.Equals(value) != true)) {
                    this.ReportDateTimeField = value;
                    this.RaisePropertyChanged("ReportDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypeField, value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceLevel {
            get {
                return this.ServiceLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceLevelField, value) != true)) {
                    this.ServiceLevelField = value;
                    this.RaisePropertyChanged("ServiceLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillId {
            get {
                return this.SkillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillIdField, value) != true)) {
                    this.SkillIdField = value;
                    this.RaisePropertyChanged("SkillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillName {
            get {
                return this.SkillNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillNameField, value) != true)) {
                    this.SkillNameField = value;
                    this.RaisePropertyChanged("SkillName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateTimeField, value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwitchName {
            get {
                return this.SwitchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SwitchNameField, value) != true)) {
                    this.SwitchNameField = value;
                    this.RaisePropertyChanged("SwitchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalAfterCallTime {
            get {
                return this.TotalAfterCallTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAfterCallTimeField, value) != true)) {
                    this.TotalAfterCallTimeField = value;
                    this.RaisePropertyChanged("TotalAfterCallTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalAux {
            get {
                return this.TotalAuxField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAuxField, value) != true)) {
                    this.TotalAuxField = value;
                    this.RaisePropertyChanged("TotalAux");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="THistoricalData.IHistoricalData")]
    public interface IHistoricalData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/GetSkillHistoricalData", ReplyAction="http://tempuri.org/IHistoricalData/GetSkillHistoricalDataResponse")]
        CMDataCollector.THistoricalData.SkillData GetSkillHistoricalData(string skillId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/GetSkillHistoricalData", ReplyAction="http://tempuri.org/IHistoricalData/GetSkillHistoricalDataResponse")]
        System.Threading.Tasks.Task<CMDataCollector.THistoricalData.SkillData> GetSkillHistoricalDataAsync(string skillId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoricalDataChannel : CMDataCollector.THistoricalData.IHistoricalData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoricalDataClient : System.ServiceModel.ClientBase<CMDataCollector.THistoricalData.IHistoricalData>, CMDataCollector.THistoricalData.IHistoricalData {
        
        public HistoricalDataClient() {
        }
        
        public HistoricalDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoricalDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricalDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricalDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CMDataCollector.THistoricalData.SkillData GetSkillHistoricalData(string skillId) {
            return base.Channel.GetSkillHistoricalData(skillId);
        }
        
        public System.Threading.Tasks.Task<CMDataCollector.THistoricalData.SkillData> GetSkillHistoricalDataAsync(string skillId) {
            return base.Channel.GetSkillHistoricalDataAsync(skillId);
        }
    }
}
