//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THistoricalData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Info", Namespace="http://schemas.datacontract.org/2004/07/THistoricalData.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(THistoricalData.SkillInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(THistoricalData.AgentInfo))]
    public partial class Info : object
    {
        
        private int AcceptableServiceLevelField;
        
        private string ExtnField;
        
        private string HybridSourceTypeField;
        
        private string IdField;
        
        private string LastUpdatedByField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcceptableServiceLevel
        {
            get
            {
                return this.AcceptableServiceLevelField;
            }
            set
            {
                this.AcceptableServiceLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extn
        {
            get
            {
                return this.ExtnField;
            }
            set
            {
                this.ExtnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HybridSourceType
        {
            get
            {
                return this.HybridSourceTypeField;
            }
            set
            {
                this.HybridSourceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy
        {
            get
            {
                return this.LastUpdatedByField;
            }
            set
            {
                this.LastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillInfo", Namespace="http://schemas.datacontract.org/2004/07/THistoricalData.Model")]
    public partial class SkillInfo : THistoricalData.Info
    {
        
        private int AbandCallsField;
        
        private int AcdCallsField;
        
        private string AvgAbandTimeField;
        
        private string AvgSpeedAnswerField;
        
        private string AvgStaffedTimeField;
        
        private string AvgTalkTimeField;
        
        private int CallsAbandonedAfterSLAThresholdField;
        
        private int CallsHandledWithinSLAThresholdField;
        
        private string DateField;
        
        private string DateIntField;
        
        private int FlowInField;
        
        private int FlowOutField;
        
        private string IntervalField;
        
        private string IntvlField;
        
        private int PassedCallsField;
        
        private System.DateTime ReportDateTimeField;
        
        private string ReportTypeField;
        
        private string SLPercentageField;
        
        private string SkillExtensionField;
        
        private string SkillIdField;
        
        private string SkillNameField;
        
        private int SpeedOfAnswerField;
        
        private string StartDateTimeField;
        
        private string SwitchNameField;
        
        private int TotalAbandTimeField;
        
        private int TotalAfterCallTimeField;
        
        private int TotalAuxTimeField;
        
        private string TotalInteractionField;
        
        private int TotalStaffedAgentsField;
        
        private int TotalStaffedTimeField;
        
        private int TotalTalkTimeField;
        
        private int TransferCallField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AbandCalls
        {
            get
            {
                return this.AbandCallsField;
            }
            set
            {
                this.AbandCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcdCalls
        {
            get
            {
                return this.AcdCallsField;
            }
            set
            {
                this.AcdCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgAbandTime
        {
            get
            {
                return this.AvgAbandTimeField;
            }
            set
            {
                this.AvgAbandTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgSpeedAnswer
        {
            get
            {
                return this.AvgSpeedAnswerField;
            }
            set
            {
                this.AvgSpeedAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgStaffedTime
        {
            get
            {
                return this.AvgStaffedTimeField;
            }
            set
            {
                this.AvgStaffedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgTalkTime
        {
            get
            {
                return this.AvgTalkTimeField;
            }
            set
            {
                this.AvgTalkTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CallsAbandonedAfterSLAThreshold
        {
            get
            {
                return this.CallsAbandonedAfterSLAThresholdField;
            }
            set
            {
                this.CallsAbandonedAfterSLAThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CallsHandledWithinSLAThreshold
        {
            get
            {
                return this.CallsHandledWithinSLAThresholdField;
            }
            set
            {
                this.CallsHandledWithinSLAThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateInt
        {
            get
            {
                return this.DateIntField;
            }
            set
            {
                this.DateIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowIn
        {
            get
            {
                return this.FlowInField;
            }
            set
            {
                this.FlowInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FlowOut
        {
            get
            {
                return this.FlowOutField;
            }
            set
            {
                this.FlowOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interval
        {
            get
            {
                return this.IntervalField;
            }
            set
            {
                this.IntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intvl
        {
            get
            {
                return this.IntvlField;
            }
            set
            {
                this.IntvlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PassedCalls
        {
            get
            {
                return this.PassedCallsField;
            }
            set
            {
                this.PassedCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDateTime
        {
            get
            {
                return this.ReportDateTimeField;
            }
            set
            {
                this.ReportDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLPercentage
        {
            get
            {
                return this.SLPercentageField;
            }
            set
            {
                this.SLPercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillExtension
        {
            get
            {
                return this.SkillExtensionField;
            }
            set
            {
                this.SkillExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillId
        {
            get
            {
                return this.SkillIdField;
            }
            set
            {
                this.SkillIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillName
        {
            get
            {
                return this.SkillNameField;
            }
            set
            {
                this.SkillNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpeedOfAnswer
        {
            get
            {
                return this.SpeedOfAnswerField;
            }
            set
            {
                this.SpeedOfAnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwitchName
        {
            get
            {
                return this.SwitchNameField;
            }
            set
            {
                this.SwitchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAbandTime
        {
            get
            {
                return this.TotalAbandTimeField;
            }
            set
            {
                this.TotalAbandTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAfterCallTime
        {
            get
            {
                return this.TotalAfterCallTimeField;
            }
            set
            {
                this.TotalAfterCallTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAuxTime
        {
            get
            {
                return this.TotalAuxTimeField;
            }
            set
            {
                this.TotalAuxTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalInteraction
        {
            get
            {
                return this.TotalInteractionField;
            }
            set
            {
                this.TotalInteractionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalStaffedAgents
        {
            get
            {
                return this.TotalStaffedAgentsField;
            }
            set
            {
                this.TotalStaffedAgentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalStaffedTime
        {
            get
            {
                return this.TotalStaffedTimeField;
            }
            set
            {
                this.TotalStaffedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalTalkTime
        {
            get
            {
                return this.TotalTalkTimeField;
            }
            set
            {
                this.TotalTalkTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransferCall
        {
            get
            {
                return this.TransferCallField;
            }
            set
            {
                this.TransferCallField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentInfo", Namespace="http://schemas.datacontract.org/2004/07/THistoricalData.Model")]
    public partial class AgentInfo : THistoricalData.Info
    {
        
        private int AcdCallsField;
        
        private string AgentIDField;
        
        private string AgentNameField;
        
        private string AvgAudioIPTimeField;
        
        private string AvgChatTimeField;
        
        private string AvgExtensionTimeField;
        
        private string AvgInteractionTimeField;
        
        private string AvgTalkTimeField;
        
        private string DateField;
        
        private string DateIntField;
        
        private int ExtensionCallsField;
        
        private string IntervalField;
        
        private string IntvlField;
        
        private System.DateTime ReportDateTimeField;
        
        private string SupervisorNameField;
        
        private int TotalAfterCallTimeField;
        
        private int TotalAudioIPField;
        
        private int TotalAudioIPTimeField;
        
        private int TotalAuxTimeField;
        
        private int TotalAvailTimeField;
        
        private int TotalChatField;
        
        private int TotalChatTimeField;
        
        private int TotalExtensionTimeField;
        
        private int TotalHoldTimeField;
        
        private string TotalInteractionField;
        
        private int TotalInteractionTimeField;
        
        private int TotalStaffedTimeField;
        
        private int TransferCallField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcdCalls
        {
            get
            {
                return this.AcdCallsField;
            }
            set
            {
                this.AcdCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentName
        {
            get
            {
                return this.AgentNameField;
            }
            set
            {
                this.AgentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgAudioIPTime
        {
            get
            {
                return this.AvgAudioIPTimeField;
            }
            set
            {
                this.AvgAudioIPTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgChatTime
        {
            get
            {
                return this.AvgChatTimeField;
            }
            set
            {
                this.AvgChatTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgExtensionTime
        {
            get
            {
                return this.AvgExtensionTimeField;
            }
            set
            {
                this.AvgExtensionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgInteractionTime
        {
            get
            {
                return this.AvgInteractionTimeField;
            }
            set
            {
                this.AvgInteractionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgTalkTime
        {
            get
            {
                return this.AvgTalkTimeField;
            }
            set
            {
                this.AvgTalkTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateInt
        {
            get
            {
                return this.DateIntField;
            }
            set
            {
                this.DateIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtensionCalls
        {
            get
            {
                return this.ExtensionCallsField;
            }
            set
            {
                this.ExtensionCallsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interval
        {
            get
            {
                return this.IntervalField;
            }
            set
            {
                this.IntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intvl
        {
            get
            {
                return this.IntvlField;
            }
            set
            {
                this.IntvlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDateTime
        {
            get
            {
                return this.ReportDateTimeField;
            }
            set
            {
                this.ReportDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorName
        {
            get
            {
                return this.SupervisorNameField;
            }
            set
            {
                this.SupervisorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAfterCallTime
        {
            get
            {
                return this.TotalAfterCallTimeField;
            }
            set
            {
                this.TotalAfterCallTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAudioIP
        {
            get
            {
                return this.TotalAudioIPField;
            }
            set
            {
                this.TotalAudioIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAudioIPTime
        {
            get
            {
                return this.TotalAudioIPTimeField;
            }
            set
            {
                this.TotalAudioIPTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAuxTime
        {
            get
            {
                return this.TotalAuxTimeField;
            }
            set
            {
                this.TotalAuxTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAvailTime
        {
            get
            {
                return this.TotalAvailTimeField;
            }
            set
            {
                this.TotalAvailTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalChat
        {
            get
            {
                return this.TotalChatField;
            }
            set
            {
                this.TotalChatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalChatTime
        {
            get
            {
                return this.TotalChatTimeField;
            }
            set
            {
                this.TotalChatTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalExtensionTime
        {
            get
            {
                return this.TotalExtensionTimeField;
            }
            set
            {
                this.TotalExtensionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalHoldTime
        {
            get
            {
                return this.TotalHoldTimeField;
            }
            set
            {
                this.TotalHoldTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalInteraction
        {
            get
            {
                return this.TotalInteractionField;
            }
            set
            {
                this.TotalInteractionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalInteractionTime
        {
            get
            {
                return this.TotalInteractionTimeField;
            }
            set
            {
                this.TotalInteractionTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalStaffedTime
        {
            get
            {
                return this.TotalStaffedTimeField;
            }
            set
            {
                this.TotalStaffedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransferCall
        {
            get
            {
                return this.TransferCallField;
            }
            set
            {
                this.TransferCallField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="THistoricalData.IHistoricalData")]
    public interface IHistoricalData
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/GetAgentHistoricalData", ReplyAction="http://tempuri.org/IHistoricalData/GetAgentHistoricalDataResponse")]
        System.Threading.Tasks.Task<THistoricalData.AgentInfo> GetAgentHistoricalDataAsync(string agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/GetSkillHistoricalData", ReplyAction="http://tempuri.org/IHistoricalData/GetSkillHistoricalDataResponse")]
        System.Threading.Tasks.Task<THistoricalData.SkillInfo> GetSkillHistoricalDataAsync(string skillId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/IsServiceRunning", ReplyAction="http://tempuri.org/IHistoricalData/IsServiceRunningResponse")]
        System.Threading.Tasks.Task<bool> IsServiceRunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricalData/ServerId", ReplyAction="http://tempuri.org/IHistoricalData/ServerIdResponse")]
        System.Threading.Tasks.Task<int> ServerIdAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IHistoricalDataChannel : THistoricalData.IHistoricalData, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HistoricalDataClient : System.ServiceModel.ClientBase<THistoricalData.IHistoricalData>, THistoricalData.IHistoricalData
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HistoricalDataClient() : 
                base(HistoricalDataClient.GetDefaultBinding(), HistoricalDataClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHistoricalData.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HistoricalDataClient(EndpointConfiguration endpointConfiguration) : 
                base(HistoricalDataClient.GetBindingForEndpoint(endpointConfiguration), HistoricalDataClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HistoricalDataClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HistoricalDataClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HistoricalDataClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HistoricalDataClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HistoricalDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<THistoricalData.AgentInfo> GetAgentHistoricalDataAsync(string agentId)
        {
            return base.Channel.GetAgentHistoricalDataAsync(agentId);
        }
        
        public System.Threading.Tasks.Task<THistoricalData.SkillInfo> GetSkillHistoricalDataAsync(string skillId)
        {
            return base.Channel.GetSkillHistoricalDataAsync(skillId);
        }
        
        public System.Threading.Tasks.Task<bool> IsServiceRunningAsync()
        {
            return base.Channel.IsServiceRunningAsync();
        }
        
        public System.Threading.Tasks.Task<int> ServerIdAsync()
        {
            return base.Channel.ServerIdAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHistoricalData))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHistoricalData))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:12345/THistoricalData/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HistoricalDataClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHistoricalData);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HistoricalDataClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHistoricalData);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHistoricalData,
        }
    }
}
