//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkQueue
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkItem", Namespace="http://schemas.datacontract.org/2004/07/TetherfiWorkAssignment")]
    public partial class WorkItem : object
    {
        
        private System.DateTime AddedTimeField;
        
        private string AgentIDField;
        
        private System.DateTime AssignedAtField;
        
        private string ChannelField;
        
        private string CreatedByField;
        
        private string CustomerIdentifierField;
        
        private string DataField;
        
        private bool IsAssignedField;
        
        private string ItemIDField;
        
        private string KeyField;
        
        private int OrderIndexField;
        
        private string ReasonField;
        
        private bool RonaEnabledField;
        
        private string RouteDateField;
        
        private string RouteTimeField;
        
        private string SkillField;
        
        private int StatusField;
        
        private string SubChannelField;
        
        private System.DateTime TTLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddedTime
        {
            get
            {
                return this.AddedTimeField;
            }
            set
            {
                this.AddedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssignedAt
        {
            get
            {
                return this.AssignedAtField;
            }
            set
            {
                this.AssignedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerIdentifier
        {
            get
            {
                return this.CustomerIdentifierField;
            }
            set
            {
                this.CustomerIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAssigned
        {
            get
            {
                return this.IsAssignedField;
            }
            set
            {
                this.IsAssignedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID
        {
            get
            {
                return this.ItemIDField;
            }
            set
            {
                this.ItemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex
        {
            get
            {
                return this.OrderIndexField;
            }
            set
            {
                this.OrderIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RonaEnabled
        {
            get
            {
                return this.RonaEnabledField;
            }
            set
            {
                this.RonaEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteDate
        {
            get
            {
                return this.RouteDateField;
            }
            set
            {
                this.RouteDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteTime
        {
            get
            {
                return this.RouteTimeField;
            }
            set
            {
                this.RouteTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skill
        {
            get
            {
                return this.SkillField;
            }
            set
            {
                this.SkillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubChannel
        {
            get
            {
                return this.SubChannelField;
            }
            set
            {
                this.SubChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TTL
        {
            get
            {
                return this.TTLField;
            }
            set
            {
                this.TTLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentTabCount", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    public partial class AgentTabCount : object
    {
        
        private string ChannelField;
        
        private int CountField;
        
        private string InteractionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InteractionType
        {
            get
            {
                return this.InteractionTypeField;
            }
            set
            {
                this.InteractionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentStaticData", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    public partial class AgentStaticData : object
    {
        
        private string LanIdField;
        
        private string LoginIdField;
        
        private string ServerField;
        
        private WorkQueue.VoiceSkillData[] SkillsField;
        
        private string StationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanId
        {
            get
            {
                return this.LanIdField;
            }
            set
            {
                this.LanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId
        {
            get
            {
                return this.LoginIdField;
            }
            set
            {
                this.LoginIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Server
        {
            get
            {
                return this.ServerField;
            }
            set
            {
                this.ServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkQueue.VoiceSkillData[] Skills
        {
            get
            {
                return this.SkillsField;
            }
            set
            {
                this.SkillsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station
        {
            get
            {
                return this.StationField;
            }
            set
            {
                this.StationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoiceSkillData", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    public partial class VoiceSkillData : object
    {
        
        private int AgentAvailableField;
        
        private int AgentsStaffedField;
        
        private int CIQ_TSField;
        
        private bool CIQ_TS_AchievedField;
        
        private int CallsInQueueField;
        
        private string NameField;
        
        private string SkillField;
        
        private string SkillGroupIdField;
        
        private int SkillLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentAvailable
        {
            get
            {
                return this.AgentAvailableField;
            }
            set
            {
                this.AgentAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentsStaffed
        {
            get
            {
                return this.AgentsStaffedField;
            }
            set
            {
                this.AgentsStaffedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIQ_TS
        {
            get
            {
                return this.CIQ_TSField;
            }
            set
            {
                this.CIQ_TSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CIQ_TS_Achieved
        {
            get
            {
                return this.CIQ_TS_AchievedField;
            }
            set
            {
                this.CIQ_TS_AchievedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CallsInQueue
        {
            get
            {
                return this.CallsInQueueField;
            }
            set
            {
                this.CallsInQueueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skill
        {
            get
            {
                return this.SkillField;
            }
            set
            {
                this.SkillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillGroupId
        {
            get
            {
                return this.SkillGroupIdField;
            }
            set
            {
                this.SkillGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkillLevel
        {
            get
            {
                return this.SkillLevelField;
            }
            set
            {
                this.SkillLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentDynamicData", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    public partial class AgentDynamicData : object
    {
        
        private WorkQueue.AgentTabCount[] AllowedChannelsField;
        
        private double IdleTimeField;
        
        private WorkQueue.Interactions[] InteractionsField;
        
        private int LastInteractionDurationField;
        
        private double OccupancyRateField;
        
        private string StatusField;
        
        private string TmacServerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkQueue.AgentTabCount[] AllowedChannels
        {
            get
            {
                return this.AllowedChannelsField;
            }
            set
            {
                this.AllowedChannelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IdleTime
        {
            get
            {
                return this.IdleTimeField;
            }
            set
            {
                this.IdleTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WorkQueue.Interactions[] Interactions
        {
            get
            {
                return this.InteractionsField;
            }
            set
            {
                this.InteractionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastInteractionDuration
        {
            get
            {
                return this.LastInteractionDurationField;
            }
            set
            {
                this.LastInteractionDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OccupancyRate
        {
            get
            {
                return this.OccupancyRateField;
            }
            set
            {
                this.OccupancyRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TmacServer
        {
            get
            {
                return this.TmacServerField;
            }
            set
            {
                this.TmacServerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Interactions", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    public partial class Interactions : object
    {
        
        private string ChannelField;
        
        private string StatusField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkQueue.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddWorkItem", ReplyAction="http://tempuri.org/IService/AddWorkItemResponse")]
        System.Threading.Tasks.Task<string> AddWorkItemAsync(string channel, string skill, string itemid, string insertBy, string subchannel, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddWorkItemSync", ReplyAction="http://tempuri.org/IService/AddWorkItemSyncResponse")]
        System.Threading.Tasks.Task<string> AddWorkItemSyncAsync(WorkQueue.WorkItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddWorkItemWithCustomerIdentifier", ReplyAction="http://tempuri.org/IService/AddWorkItemWithCustomerIdentifierResponse")]
        System.Threading.Tasks.Task<string> AddWorkItemWithCustomerIdentifierAsync(string channel, string skill, string itemid, string insertBy, string subchannel, string customerIdentifier, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearAllQueue", ReplyAction="http://tempuri.org/IService/ClearAllQueueResponse")]
        System.Threading.Tasks.Task ClearAllQueueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearQueue", ReplyAction="http://tempuri.org/IService/ClearQueueResponse")]
        System.Threading.Tasks.Task<int> ClearQueueAsync(string queue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetQueueCount", ReplyAction="http://tempuri.org/IService/GetQueueCountResponse")]
        System.Threading.Tasks.Task<string> GetQueueCountAsync(string queue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetQueueDetails", ReplyAction="http://tempuri.org/IService/GetQueueDetailsResponse")]
        System.Threading.Tasks.Task<string> GetQueueDetailsAsync(string queue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkItem", ReplyAction="http://tempuri.org/IService/GetWorkItemResponse")]
        System.Threading.Tasks.Task<string> GetWorkItemAsync(string channel, string agentid, string[] skills, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkItemByLimitAll", ReplyAction="http://tempuri.org/IService/GetWorkItemByLimitAllResponse")]
        System.Threading.Tasks.Task<string> GetWorkItemByLimitAllAsync(System.Collections.Generic.Dictionary<string, int> channelCount, string agentid, string[] skills, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkItemBySkillPriority", ReplyAction="http://tempuri.org/IService/GetWorkItemBySkillPriorityResponse")]
        System.Threading.Tasks.Task<string> GetWorkItemBySkillPriorityAsync(WorkQueue.AgentTabCount[] agentTabCounts, string agentid, string[] skills, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkItems", ReplyAction="http://tempuri.org/IService/GetWorkItemsResponse")]
        System.Threading.Tasks.Task<string> GetWorkItemsAsync(string channel, string[] skills);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWorkItemsBySubChannel", ReplyAction="http://tempuri.org/IService/GetWorkItemsBySubChannelResponse")]
        System.Threading.Tasks.Task<string> GetWorkItemsBySubChannelAsync(string subchannel, string[] skills);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PullWorkItemForAgentByChannelAndItemID", ReplyAction="http://tempuri.org/IService/PullWorkItemForAgentByChannelAndItemIDResponse")]
        System.Threading.Tasks.Task<string> PullWorkItemForAgentByChannelAndItemIDAsync(string channel, string itemid, string agentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PullWorkItemForAgentByGlobalKey", ReplyAction="http://tempuri.org/IService/PullWorkItemForAgentByGlobalKeyResponse")]
        System.Threading.Tasks.Task<string> PullWorkItemForAgentByGlobalKeyAsync(string key, string agentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PullWorkItemsForAgent", ReplyAction="http://tempuri.org/IService/PullWorkItemsForAgentResponse")]
        System.Threading.Tasks.Task<string> PullWorkItemsForAgentAsync(string itemid, string channel, string skill, string datacontains, string subchannel, string customerid, string agentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PullWorkItemsForAgentByChannelAndCustomerId", ReplyAction="http://tempuri.org/IService/PullWorkItemsForAgentByChannelAndCustomerIdResponse")]
        System.Threading.Tasks.Task<string> PullWorkItemsForAgentByChannelAndCustomerIdAsync(string channel, string customerid, string agentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReloadEmailQueue", ReplyAction="http://tempuri.org/IService/ReloadEmailQueueResponse")]
        System.Threading.Tasks.Task ReloadEmailQueueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ReloadQueue", ReplyAction="http://tempuri.org/IService/ReloadQueueResponse")]
        System.Threading.Tasks.Task ReloadQueueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveWorkItemByItemIDAndChannel", ReplyAction="http://tempuri.org/IService/RemoveWorkItemByItemIDAndChannelResponse")]
        System.Threading.Tasks.Task<int> RemoveWorkItemByItemIDAndChannelAsync(string channel, string itemid, string removedBy, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveWorkItemByKey", ReplyAction="http://tempuri.org/IService/RemoveWorkItemByKeyResponse")]
        System.Threading.Tasks.Task<int> RemoveWorkItemByKeyAsync(string key, string removedBy, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveWorkItemSync", ReplyAction="http://tempuri.org/IService/RemoveWorkItemSyncResponse")]
        System.Threading.Tasks.Task<string> RemoveWorkItemSyncAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchWorkItems", ReplyAction="http://tempuri.org/IService/SearchWorkItemsResponse")]
        System.Threading.Tasks.Task<string> SearchWorkItemsAsync(string itemid, string channel, string skill, string datacontains, string subchannel, string customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetWorkItemAssignedToAgent", ReplyAction="http://tempuri.org/IService/SetWorkItemAssignedToAgentResponse")]
        System.Threading.Tasks.Task SetWorkItemAssignedToAgentAsync(string channel, string itemid, string agentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateLoggedInAgentsData", ReplyAction="http://tempuri.org/IService/UpdateLoggedInAgentsDataResponse")]
        System.Threading.Tasks.Task<bool> UpdateLoggedInAgentsDataAsync(string agentId, string type, WorkQueue.AgentStaticData staticData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateEligibleAgentsData", ReplyAction="http://tempuri.org/IService/UpdateEligibleAgentsDataResponse")]
        System.Threading.Tasks.Task<bool> UpdateEligibleAgentsDataAsync(System.Collections.Generic.Dictionary<string, WorkQueue.AgentDynamicData> dynamicData, string tmacServer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateWorkItemStatus", ReplyAction="http://tempuri.org/IService/UpdateWorkItemStatusResponse")]
        System.Threading.Tasks.Task UpdateWorkItemStatusAsync(string channel, string itemid, string updateby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateWorkItemStatusSync", ReplyAction="http://tempuri.org/IService/UpdateWorkItemStatusSyncResponse")]
        System.Threading.Tasks.Task UpdateWorkItemStatusSyncAsync(string key, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsProcessingWorkItems", ReplyAction="http://tempuri.org/IService/IsProcessingWorkItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, bool>> IsProcessingWorkItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : WorkQueue.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WorkQueue.IService>, WorkQueue.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> AddWorkItemAsync(string channel, string skill, string itemid, string insertBy, string subchannel, string data)
        {
            return base.Channel.AddWorkItemAsync(channel, skill, itemid, insertBy, subchannel, data);
        }
        
        public System.Threading.Tasks.Task<string> AddWorkItemSyncAsync(WorkQueue.WorkItem item)
        {
            return base.Channel.AddWorkItemSyncAsync(item);
        }
        
        public System.Threading.Tasks.Task<string> AddWorkItemWithCustomerIdentifierAsync(string channel, string skill, string itemid, string insertBy, string subchannel, string customerIdentifier, string data)
        {
            return base.Channel.AddWorkItemWithCustomerIdentifierAsync(channel, skill, itemid, insertBy, subchannel, customerIdentifier, data);
        }
        
        public System.Threading.Tasks.Task ClearAllQueueAsync()
        {
            return base.Channel.ClearAllQueueAsync();
        }
        
        public System.Threading.Tasks.Task<int> ClearQueueAsync(string queue)
        {
            return base.Channel.ClearQueueAsync(queue);
        }
        
        public System.Threading.Tasks.Task<string> GetQueueCountAsync(string queue)
        {
            return base.Channel.GetQueueCountAsync(queue);
        }
        
        public System.Threading.Tasks.Task<string> GetQueueDetailsAsync(string queue)
        {
            return base.Channel.GetQueueDetailsAsync(queue);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkItemAsync(string channel, string agentid, string[] skills, string status)
        {
            return base.Channel.GetWorkItemAsync(channel, agentid, skills, status);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkItemByLimitAllAsync(System.Collections.Generic.Dictionary<string, int> channelCount, string agentid, string[] skills, string status)
        {
            return base.Channel.GetWorkItemByLimitAllAsync(channelCount, agentid, skills, status);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkItemBySkillPriorityAsync(WorkQueue.AgentTabCount[] agentTabCounts, string agentid, string[] skills, string status)
        {
            return base.Channel.GetWorkItemBySkillPriorityAsync(agentTabCounts, agentid, skills, status);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkItemsAsync(string channel, string[] skills)
        {
            return base.Channel.GetWorkItemsAsync(channel, skills);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkItemsBySubChannelAsync(string subchannel, string[] skills)
        {
            return base.Channel.GetWorkItemsBySubChannelAsync(subchannel, skills);
        }
        
        public System.Threading.Tasks.Task<string> PullWorkItemForAgentByChannelAndItemIDAsync(string channel, string itemid, string agentid)
        {
            return base.Channel.PullWorkItemForAgentByChannelAndItemIDAsync(channel, itemid, agentid);
        }
        
        public System.Threading.Tasks.Task<string> PullWorkItemForAgentByGlobalKeyAsync(string key, string agentid)
        {
            return base.Channel.PullWorkItemForAgentByGlobalKeyAsync(key, agentid);
        }
        
        public System.Threading.Tasks.Task<string> PullWorkItemsForAgentAsync(string itemid, string channel, string skill, string datacontains, string subchannel, string customerid, string agentid)
        {
            return base.Channel.PullWorkItemsForAgentAsync(itemid, channel, skill, datacontains, subchannel, customerid, agentid);
        }
        
        public System.Threading.Tasks.Task<string> PullWorkItemsForAgentByChannelAndCustomerIdAsync(string channel, string customerid, string agentid)
        {
            return base.Channel.PullWorkItemsForAgentByChannelAndCustomerIdAsync(channel, customerid, agentid);
        }
        
        public System.Threading.Tasks.Task ReloadEmailQueueAsync()
        {
            return base.Channel.ReloadEmailQueueAsync();
        }
        
        public System.Threading.Tasks.Task ReloadQueueAsync()
        {
            return base.Channel.ReloadQueueAsync();
        }
        
        public System.Threading.Tasks.Task<int> RemoveWorkItemByItemIDAndChannelAsync(string channel, string itemid, string removedBy, string reason)
        {
            return base.Channel.RemoveWorkItemByItemIDAndChannelAsync(channel, itemid, removedBy, reason);
        }
        
        public System.Threading.Tasks.Task<int> RemoveWorkItemByKeyAsync(string key, string removedBy, string reason)
        {
            return base.Channel.RemoveWorkItemByKeyAsync(key, removedBy, reason);
        }
        
        public System.Threading.Tasks.Task<string> RemoveWorkItemSyncAsync(string key)
        {
            return base.Channel.RemoveWorkItemSyncAsync(key);
        }
        
        public System.Threading.Tasks.Task<string> SearchWorkItemsAsync(string itemid, string channel, string skill, string datacontains, string subchannel, string customerid)
        {
            return base.Channel.SearchWorkItemsAsync(itemid, channel, skill, datacontains, subchannel, customerid);
        }
        
        public System.Threading.Tasks.Task SetWorkItemAssignedToAgentAsync(string channel, string itemid, string agentid)
        {
            return base.Channel.SetWorkItemAssignedToAgentAsync(channel, itemid, agentid);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateLoggedInAgentsDataAsync(string agentId, string type, WorkQueue.AgentStaticData staticData)
        {
            return base.Channel.UpdateLoggedInAgentsDataAsync(agentId, type, staticData);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEligibleAgentsDataAsync(System.Collections.Generic.Dictionary<string, WorkQueue.AgentDynamicData> dynamicData, string tmacServer)
        {
            return base.Channel.UpdateEligibleAgentsDataAsync(dynamicData, tmacServer);
        }
        
        public System.Threading.Tasks.Task UpdateWorkItemStatusAsync(string channel, string itemid, string updateby)
        {
            return base.Channel.UpdateWorkItemStatusAsync(channel, itemid, updateby);
        }
        
        public System.Threading.Tasks.Task UpdateWorkItemStatusSyncAsync(string key, int status)
        {
            return base.Channel.UpdateWorkItemStatusSyncAsync(key, status);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, bool>> IsProcessingWorkItemsAsync()
        {
            return base.Channel.IsProcessingWorkItemsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:17000/WorkQueue1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
